'use strict';

/**
 * Builds data/seed/*.json from the curated catalogue below.
 *
 * The original API was backed by an IMDB-derived dataset hosted on PlanetScale,
 * whose free tier shut down in April 2024. This is a small hand-curated stand-in
 * so the project runs offline. It is SAMPLE DATA: titles, years and credits are
 * real, ratings and box-office figures are approximate and rounded.
 *
 * Run with:  node scripts/build-seed.js
 */

const fs = require('fs');
const path = require('path');

// [tconst, title, year, runtime, genres, country, rated, boxoffice,
//  imdb, rottenTomatoes, metacritic, plot, director, cast]
const FILMS = [
  ['tt0111161', 'The Shawshank Redemption', 1994, 142, 'Drama', 'United States', 'R', 28884504, 9.3, 89, 82,
    'A banker convicted of a murder he did not commit builds an unlikely friendship over two decades inside Shawshank State Penitentiary.',
    'Frank Darabont', ['Tim Robbins:Andy Dufresne', 'Morgan Freeman:Ellis Boyd Redding', 'Bob Gunton:Warden Norton', 'William Sadler:Heywood']],
  ['tt0110912', 'Pulp Fiction', 1994, 154, 'Crime,Drama', 'United States', 'R', 213928762, 8.9, 92, 95,
    'Three loosely connected Los Angeles crime stories — two hit men, a boxer and a mob wife — unfold out of order and collide.',
    'Quentin Tarantino', ['John Travolta:Vincent Vega', 'Samuel L. Jackson:Jules Winnfield', 'Uma Thurman:Mia Wallace', 'Bruce Willis:Butch Coolidge']],
  ['tt0108052', "Schindler's List", 1993, 195, 'Biography,Drama,History', 'United States', 'R', 322161245, 9.0, 98, 95,
    'A German industrialist gradually turns his enamelware factory into a refuge, saving more than a thousand Polish Jews from the camps.',
    'Steven Spielberg', ['Liam Neeson:Oskar Schindler', 'Ben Kingsley:Itzhak Stern', 'Ralph Fiennes:Amon Goeth']],
  ['tt0109830', 'Forrest Gump', 1994, 142, 'Drama,Romance', 'United States', 'PG-13', 678222284, 8.8, 74, 82,
    'An Alabama man with a gentle disposition and a remarkable gift for being present drifts through three decades of American history.',
    'Robert Zemeckis', ['Tom Hanks:Forrest Gump', 'Robin Wright:Jenny Curran', 'Gary Sinise:Lieutenant Dan Taylor', 'Sally Field:Mrs. Gump']],
  ['tt0102926', 'The Silence of the Lambs', 1991, 118, 'Crime,Drama,Thriller', 'United States', 'R', 272742922, 8.6, 95, 86,
    'A trainee FBI agent seeks the counsel of an imprisoned cannibal psychiatrist to catch another serial killer still at large.',
    'Jonathan Demme', ['Jodie Foster:Clarice Starling', 'Anthony Hopkins:Dr. Hannibal Lecter', 'Scott Glenn:Jack Crawford']],
  ['tt0114369', 'Se7en', 1995, 127, 'Crime,Drama,Mystery', 'United States', 'R', 327333559, 8.6, 82, 65,
    'Two detectives, one retiring and one newly arrived, hunt a killer staging his murders around the seven deadly sins.',
    'David Fincher', ['Brad Pitt:Detective David Mills', 'Morgan Freeman:Detective William Somerset', 'Gwyneth Paltrow:Tracy Mills', 'Kevin Spacey:John Doe']],
  ['tt0137523', 'Fight Club', 1999, 139, 'Drama', 'United States', 'R', 101209702, 8.8, 79, 67,
    'An insomniac office worker and a soap salesman form an underground fighting club that grows into something far stranger.',
    'David Fincher', ['Edward Norton:The Narrator', 'Brad Pitt:Tyler Durden', 'Helena Bonham Carter:Marla Singer']],
  ['tt0133093', 'The Matrix', 1999, 136, 'Action,Sci-Fi', 'United States', 'R', 467222824, 8.7, 83, 73,
    'A programmer discovers that everyday reality is a simulation and joins a rebellion fighting the machines that maintain it.',
    'Lana Wachowski', ['Keanu Reeves:Neo', 'Laurence Fishburne:Morpheus', 'Carrie-Anne Moss:Trinity', 'Hugo Weaving:Agent Smith']],
  ['tt0120815', 'Saving Private Ryan', 1998, 169, 'Drama,War', 'United States', 'R', 482349603, 8.6, 93, 91,
    'After the Normandy landings, a squad of US soldiers pushes behind enemy lines to bring one paratrooper home.',
    'Steven Spielberg', ['Tom Hanks:Captain Miller', 'Tom Sizemore:Sergeant Horvath', 'Matt Damon:Private James Ryan']],
  ['tt0120737', 'The Lord of the Rings: The Fellowship of the Ring', 2001, 178, 'Adventure,Drama,Fantasy', 'New Zealand', 'PG-13', 897690072, 8.9, 91, 92,
    'A hobbit inherits a ring of terrible power and sets out with eight companions to carry it towards the fire that made it.',
    'Peter Jackson', ['Elijah Wood:Frodo Baggins', 'Ian McKellen:Gandalf', 'Viggo Mortensen:Aragorn', 'Sean Astin:Samwise Gamgee']],
  ['tt0167261', 'The Lord of the Rings: The Two Towers', 2002, 179, 'Adventure,Drama,Fantasy', 'New Zealand', 'PG-13', 947944663, 8.8, 95, 87,
    'The broken fellowship presses on as Rohan prepares for a siege and two hobbits follow a treacherous guide toward Mordor.',
    'Peter Jackson', ['Elijah Wood:Frodo Baggins', 'Ian McKellen:Gandalf', 'Viggo Mortensen:Aragorn', 'Andy Serkis:Gollum']],
  ['tt0167260', 'The Lord of the Rings: The Return of the King', 2003, 201, 'Adventure,Drama,Fantasy', 'New Zealand', 'PG-13', 1146030912, 9.0, 93, 94,
    'Gondor makes its last stand while two hobbits climb the final slope of Mount Doom with the ring.',
    'Peter Jackson', ['Elijah Wood:Frodo Baggins', 'Ian McKellen:Gandalf', 'Viggo Mortensen:Aragorn', 'Sean Astin:Samwise Gamgee']],
  ['tt0468569', 'The Dark Knight', 2008, 152, 'Action,Crime,Drama', 'United States', 'PG-13', 1006234167, 9.0, 94, 84,
    'Batman, a crusading district attorney and a weary police lieutenant face an anarchist who wants to prove that anyone can be broken.',
    'Christopher Nolan', ['Christian Bale:Bruce Wayne', 'Heath Ledger:The Joker', 'Aaron Eckhart:Harvey Dent', 'Gary Oldman:James Gordon']],
  ['tt0372784', 'Batman Begins', 2005, 140, 'Action,Crime,Drama', 'United States', 'PG-13', 373413297, 8.2, 84, 70,
    'A billionaire returns to a corrupt Gotham after years abroad and builds a symbol out of the fear that has followed him since childhood.',
    'Christopher Nolan', ['Christian Bale:Bruce Wayne', 'Michael Caine:Alfred Pennyworth', 'Liam Neeson:Ras al Ghul', 'Cillian Murphy:Dr. Jonathan Crane']],
  ['tt1375666', 'Inception', 2010, 148, 'Action,Adventure,Sci-Fi', 'United States', 'PG-13', 836848102, 8.8, 87, 74,
    'A thief who steals secrets from inside dreams is offered his freedom in exchange for planting an idea instead of taking one.',
    'Christopher Nolan', ['Leonardo DiCaprio:Dom Cobb', 'Joseph Gordon-Levitt:Arthur', 'Elliot Page:Ariadne', 'Tom Hardy:Eames']],
  ['tt0816692', 'Interstellar', 2014, 169, 'Adventure,Drama,Sci-Fi', 'United States', 'PG-13', 731000000, 8.7, 73, 74,
    'With Earth’s harvests failing, a former pilot leaves his children behind to fly through a wormhole in search of a new world.',
    'Christopher Nolan', ['Matthew McConaughey:Cooper', 'Anne Hathaway:Brand', 'Jessica Chastain:Murph', 'Michael Caine:Professor Brand']],
  ['tt0209144', 'Memento', 2000, 113, 'Mystery,Thriller', 'United States', 'R', 39723096, 8.4, 94, 83,
    'A man who cannot form new memories hunts his wife’s killer using tattoos, photographs and notes he no longer remembers writing.',
    'Christopher Nolan', ['Guy Pearce:Leonard Shelby', 'Carrie-Anne Moss:Natalie', 'Joe Pantoliano:Teddy']],
  ['tt0482571', 'The Prestige', 2006, 130, 'Drama,Mystery,Sci-Fi', 'United States', 'PG-13', 109676311, 8.5, 76, 66,
    'Two Victorian stage magicians ruin each other over the course of a rivalry that neither will concede.',
    'Christopher Nolan', ['Christian Bale:Alfred Borden', 'Hugh Jackman:Robert Angier', 'Michael Caine:Cutter', 'Scarlett Johansson:Olivia Wenscombe']],
  ['tt0172495', 'Gladiator', 2000, 155, 'Action,Adventure,Drama', 'United States', 'R', 465361176, 8.5, 80, 67,
    'A Roman general betrayed and sold into slavery fights his way up the arena towards the emperor who destroyed his family.',
    'Ridley Scott', ['Russell Crowe:Maximus', 'Joaquin Phoenix:Commodus', 'Connie Nielsen:Lucilla', 'Oliver Reed:Proximo']],
  ['tt0338013', 'Eternal Sunshine of the Spotless Mind', 2004, 108, 'Drama,Romance,Sci-Fi', 'United States', 'R', 74032585, 8.3, 92, 89,
    'A man undergoing a procedure to erase an ex-girlfriend from his memory changes his mind halfway through, from inside the memories.',
    'Michel Gondry', ['Jim Carrey:Joel Barish', 'Kate Winslet:Clementine Kruczynski', 'Kirsten Dunst:Mary', 'Mark Ruffalo:Stan']],
  ['tt0407887', 'The Departed', 2006, 151, 'Crime,Drama,Thriller', 'United States', 'R', 291465034, 8.5, 90, 85,
    'An undercover officer inside a Boston crime family and a mole inside the police race to expose each other first.',
    'Martin Scorsese', ['Leonardo DiCaprio:Billy Costigan', 'Matt Damon:Colin Sullivan', 'Jack Nicholson:Frank Costello', 'Mark Wahlberg:Sergeant Dignam']],
  ['tt0993846', 'The Wolf of Wall Street', 2013, 180, 'Biography,Comedy,Crime', 'United States', 'R', 392000694, 8.2, 80, 75,
    'A penny-stock broker builds a fortune on fraud and spends it as fast as it arrives.',
    'Martin Scorsese', ['Leonardo DiCaprio:Jordan Belfort', 'Jonah Hill:Donnie Azoff', 'Margot Robbie:Naomi Lapaglia', 'Matthew McConaughey:Mark Hanna']],
  ['tt1130884', 'Shutter Island', 2010, 138, 'Mystery,Thriller', 'United States', 'R', 294805697, 8.2, 69, 63,
    'Two US marshals investigate a disappearance from a hospital for the criminally insane on a storm-cut island.',
    'Martin Scorsese', ['Leonardo DiCaprio:Teddy Daniels', 'Mark Ruffalo:Chuck Aule', 'Ben Kingsley:Dr. Cawley']],
  ['tt0361748', 'Inglourious Basterds', 2009, 153, 'Adventure,Drama,War', 'United States', 'R', 321457747, 8.3, 89, 69,
    'A Jewish cinema owner in occupied Paris and a squad of Allied soldiers separately plot to end the war in one evening.',
    'Quentin Tarantino', ['Brad Pitt:Lieutenant Aldo Raine', 'Christoph Waltz:Colonel Hans Landa', 'Melanie Laurent:Shosanna Dreyfus', 'Diane Kruger:Bridget von Hammersmark']],
  ['tt1853728', 'Django Unchained', 2012, 165, 'Drama,Western', 'United States', 'R', 426074373, 8.5, 86, 81,
    'A freed slave and a German bounty hunter ride into Mississippi to buy back the wife a plantation owner will not sell.',
    'Quentin Tarantino', ['Jamie Foxx:Django', 'Christoph Waltz:Dr. King Schultz', 'Leonardo DiCaprio:Calvin Candie', 'Samuel L. Jackson:Stephen']],
  ['tt2582802', 'Whiplash', 2014, 106, 'Drama,Music', 'United States', 'R', 49000000, 8.5, 94, 89,
    'A jazz drummer at a cutthroat conservatory is pushed towards greatness, or a breakdown, by a conductor who sees no difference.',
    'Damien Chazelle', ['Miles Teller:Andrew Neiman', 'J.K. Simmons:Terence Fletcher', 'Paul Reiser:Jim Neiman']],
  ['tt3783958', 'La La Land', 2016, 128, 'Comedy,Drama,Music', 'United States', 'PG-13', 448000000, 8.0, 91, 94,
    'A jazz pianist and an aspiring actress fall in love in Los Angeles while their ambitions pull in opposite directions.',
    'Damien Chazelle', ['Ryan Gosling:Sebastian', 'Emma Stone:Mia', 'John Legend:Keith', 'Rosemarie DeWitt:Laura']],
  ['tt6751668', 'Parasite', 2019, 132, 'Drama,Thriller', 'South Korea', 'R', 262000000, 8.5, 99, 96,
    'A family living in a semi-basement talks its way one by one into the household of a far wealthier family.',
    'Bong Joon Ho', ['Song Kang-ho:Ki-taek', 'Lee Sun-kyun:Mr. Park', 'Cho Yeo-jeong:Yeon-kyo', 'Choi Woo-shik:Ki-woo']],
  ['tt1291584', 'Warrior', 2011, 140, 'Action,Drama,Sport', 'United States', 'PG-13', 23100000, 8.1, 83, 71,
    'Two estranged brothers, a teacher and a marine, end up on opposite sides of the same mixed martial arts tournament.',
    'Gavin O’Connor', ['Tom Hardy:Tommy Conlon', 'Joel Edgerton:Brendan Conlon', 'Nick Nolte:Paddy Conlon']],
  ['tt1392190', 'Mad Max: Fury Road', 2015, 120, 'Action,Adventure,Sci-Fi', 'Australia', 'R', 380000000, 8.1, 97, 90,
    'A drifter and a runaway commander flee a warlord across the desert in a single sustained chase.',
    'George Miller', ['Tom Hardy:Max Rockatansky', 'Charlize Theron:Imperator Furiosa', 'Nicholas Hoult:Nux', 'Hugh Keays-Byrne:Immortan Joe']],
  ['tt2267998', 'Gone Girl', 2014, 149, 'Drama,Mystery,Thriller', 'United States', 'R', 369000000, 8.1, 87, 79,
    'A man becomes the prime suspect when his wife vanishes on their fifth anniversary and the coverage turns against him.',
    'David Fincher', ['Ben Affleck:Nick Dunne', 'Rosamund Pike:Amy Dunne', 'Neil Patrick Harris:Desi Collings', 'Carrie Coon:Margo Dunne']],
  ['tt0114814', 'The Usual Suspects', 1995, 106, 'Crime,Drama,Mystery', 'United States', 'R', 23341568, 8.5, 88, 77,
    'The sole survivor of a dockside massacre spins a story for customs agents about a criminal nobody can prove exists.',
    'Bryan Singer', ['Kevin Spacey:Roger Kint', 'Gabriel Byrne:Dean Keaton', 'Chazz Palminteri:Dave Kujan', 'Benicio del Toro:Fred Fenster']],
  ['tt0169547', 'American Beauty', 1999, 122, 'Drama', 'United States', 'R', 356296601, 8.3, 87, 84,
    'A suburban father in freefall quits his job, blackmails his boss and fixates on his daughter’s classmate.',
    'Sam Mendes', ['Kevin Spacey:Lester Burnham', 'Annette Bening:Carolyn Burnham', 'Thora Birch:Jane Burnham', 'Wes Bentley:Ricky Fitts']],
  ['tt0253474', 'The Pianist', 2002, 150, 'Biography,Drama,Music', 'France', 'R', 120072577, 8.5, 95, 85,
    'A Polish-Jewish pianist survives the destruction of the Warsaw ghetto by hiding in the ruins of the city.',
    'Roman Polanski', ['Adrien Brody:Wladyslaw Szpilman', 'Thomas Kretschmann:Captain Hosenfeld', 'Frank Finlay:Father']],
  ['tt0405094', 'The Lives of Others', 2006, 137, 'Drama,Mystery,Thriller', 'Germany', 'R', 77400000, 8.4, 92, 89,
    'A Stasi officer assigned to bug a playwright’s flat is slowly changed by what he hears through the headphones.',
    'Florian Henckel von Donnersmarck', ['Ulrich Muhe:Gerd Wiesler', 'Martina Gedeck:Christa-Maria Sieland', 'Sebastian Koch:Georg Dreyman']],
  ['tt0245429', 'Spirited Away', 2001, 125, 'Animation,Adventure,Family', 'Japan', 'PG', 395800000, 8.6, 96, 96,
    'A sullen girl whose parents have been turned into pigs takes work in a bathhouse for spirits to win them back.',
    'Hayao Miyazaki', ['Rumi Hiiragi:Chihiro', 'Miyu Irino:Haku', 'Mari Natsuki:Yubaba']],
  ['tt0347149', "Howl's Moving Castle", 2004, 119, 'Animation,Adventure,Family', 'Japan', 'PG', 236000000, 8.2, 87, 82,
    'A hatter cursed into old age takes shelter in the walking castle of a wizard the kingdom is trying to conscript.',
    'Hayao Miyazaki', ['Chieko Baisho:Sophie', 'Takuya Kimura:Howl', 'Akihiro Miwa:Witch of the Waste']],
  ['tt0096283', 'My Neighbor Totoro', 1988, 86, 'Animation,Family,Fantasy', 'Japan', 'G', 41000000, 8.1, 94, 86,
    'Two sisters who move to the countryside while their mother is ill befriend the forest spirits living next door.',
    'Hayao Miyazaki', ['Noriko Hidaka:Satsuki', 'Chika Sakamoto:Mei', 'Hitoshi Takagi:Totoro']],
  ['tt0114709', 'Toy Story', 1995, 81, 'Animation,Adventure,Comedy', 'United States', 'G', 394436586, 8.3, 100, 96,
    'A cowboy doll’s place as favourite toy is threatened by a new spaceman figure who does not know he is a toy.',
    'John Lasseter', ['Tom Hanks:Woody', 'Tim Allen:Buzz Lightyear', 'Don Rickles:Mr. Potato Head']],
  ['tt0435761', 'Toy Story 3', 2010, 103, 'Animation,Adventure,Comedy', 'United States', 'G', 1067000000, 8.3, 98, 92,
    'With their owner leaving for college, the toys are donated to a daycare run on strict lines by a strawberry-scented bear.',
    'Lee Unkrich', ['Tom Hanks:Woody', 'Tim Allen:Buzz Lightyear', 'Joan Cusack:Jessie', 'Ned Beatty:Lotso']],
  ['tt0198781', 'Monsters, Inc.', 2001, 92, 'Animation,Adventure,Comedy', 'United States', 'G', 579000000, 8.1, 96, 79,
    'Two monsters whose job is scaring children have to hide one who wanders back through the closet door.',
    'Pete Docter', ['John Goodman:Sulley', 'Billy Crystal:Mike Wazowski', 'Mary Gibbs:Boo', 'Steve Buscemi:Randall']],
  ['tt0266543', 'Finding Nemo', 2003, 100, 'Animation,Adventure,Comedy', 'United States', 'G', 940000000, 8.2, 99, 90,
    'An anxious clownfish crosses the ocean with a forgetful companion to find the son taken by a diver.',
    'Andrew Stanton', ['Albert Brooks:Marlin', 'Ellen DeGeneres:Dory', 'Alexander Gould:Nemo', 'Willem Dafoe:Gill']],
  ['tt0910970', 'WALL-E', 2008, 98, 'Animation,Adventure,Family', 'United States', 'G', 521000000, 8.4, 95, 95,
    'The last rubbish-compacting robot on an abandoned Earth follows a survey probe into space.',
    'Andrew Stanton', ['Ben Burtt:WALL-E', 'Elissa Knight:EVE', 'Jeff Garlin:Captain', 'Sigourney Weaver:Ship Computer']],
  ['tt1049413', 'Up', 2009, 96, 'Animation,Adventure,Comedy', 'United States', 'PG', 735000000, 8.3, 98, 88,
    'A widowed balloon salesman flies his house to South America and finds a scout has come along.',
    'Pete Docter', ['Edward Asner:Carl Fredricksen', 'Jordan Nagai:Russell', 'Christopher Plummer:Charles Muntz']],
  ['tt2096673', 'Inside Out', 2015, 95, 'Animation,Adventure,Comedy', 'United States', 'PG', 858000000, 8.1, 98, 94,
    'Five emotions running an eleven-year-old’s mind lose two of their number just as her family moves cities.',
    'Pete Docter', ['Amy Poehler:Joy', 'Phyllis Smith:Sadness', 'Lewis Black:Anger', 'Bill Hader:Fear']],
  ['tt0317705', 'The Incredibles', 2004, 115, 'Animation,Action,Adventure', 'United States', 'PG', 631000000, 8.0, 97, 90,
    'A superhero family living undercover in the suburbs is drawn back into costume by an admirer turned rival.',
    'Brad Bird', ['Craig T. Nelson:Mr. Incredible', 'Holly Hunter:Elastigirl', 'Samuel L. Jackson:Frozone', 'Jason Lee:Syndrome']],
  ['tt0382932', 'Ratatouille', 2007, 111, 'Animation,Adventure,Comedy', 'United States', 'G', 623000000, 8.1, 96, 96,
    'A rat with an exceptional palate cooks through a hapless kitchen porter at a declining Paris restaurant.',
    'Brad Bird', ['Patton Oswalt:Remy', 'Lou Romano:Linguini', 'Peter O’Toole:Anton Ego', 'Janeane Garofalo:Colette']],
  ['tt0892769', 'How to Train Your Dragon', 2010, 98, 'Animation,Action,Adventure', 'United States', 'PG', 495000000, 8.1, 99, 75,
    'A viking teenager who cannot bring himself to kill a downed dragon secretly builds it a new tail instead.',
    'Dean DeBlois', ['Jay Baruchel:Hiccup', 'Gerard Butler:Stoick', 'America Ferrera:Astrid', 'Craig Ferguson:Gobber']],
  ['tt0245712', 'Amores Perros', 2000, 154, 'Drama,Thriller', 'Mexico', 'R', 20900000, 8.1, 92, 83,
    'A car crash in Mexico City ties together a dog fighter, a model and a homeless assassin.',
    'Alejandro G. Inarritu', ['Gael Garcia Bernal:Octavio', 'Emilio Echevarria:El Chivo', 'Goya Toledo:Valeria']],
  ['tt1663202', 'The Revenant', 2015, 156, 'Action,Adventure,Drama', 'United States', 'R', 533000000, 8.0, 78, 76,
    'A frontier trapper mauled and left for dead crawls back through winter after the men who abandoned him.',
    'Alejandro G. Inarritu', ['Leonardo DiCaprio:Hugh Glass', 'Tom Hardy:John Fitzgerald', 'Domhnall Gleeson:Captain Henry', 'Will Poulter:Jim Bridger']],
  ['tt2278388', 'The Grand Budapest Hotel', 2014, 99, 'Adventure,Comedy,Crime', 'Germany', 'R', 173000000, 8.1, 92, 88,
    'A legendary concierge and his lobby boy are pulled into a fight over a stolen painting and a disputed will.',
    'Wes Anderson', ['Ralph Fiennes:M. Gustave', 'Tony Revolori:Zero Moustafa', 'Adrien Brody:Dmitri', 'Saoirse Ronan:Agatha']],
  ['tt0265666', 'The Royal Tenenbaums', 2001, 110, 'Comedy,Drama', 'United States', 'R', 71400000, 7.6, 81, 76,
    'A father who walked out on three gifted children announces he is dying in order to move back in.',
    'Wes Anderson', ['Gene Hackman:Royal Tenenbaum', 'Anjelica Huston:Etheline', 'Ben Stiller:Chas', 'Gwyneth Paltrow:Margot']],
  ['tt0286716', 'Spider-Man', 2002, 121, 'Action,Adventure,Sci-Fi', 'United States', 'PG-13', 825000000, 7.4, 90, 73,
    'A bitten teenager learns what his new abilities cost him, and what his father’s employer has become.',
    'Sam Raimi', ['Tobey Maguire:Peter Parker', 'Willem Dafoe:Norman Osborn', 'Kirsten Dunst:Mary Jane Watson', 'James Franco:Harry Osborn']],
  ['tt0316654', 'Spider-Man 2', 2004, 127, 'Action,Adventure,Sci-Fi', 'United States', 'PG-13', 789000000, 7.5, 93, 83,
    'Peter Parker is failing at everything except the job he keeps trying to quit, and a fusion accident makes it worse.',
    'Sam Raimi', ['Tobey Maguire:Peter Parker', 'Alfred Molina:Doc Ock', 'Kirsten Dunst:Mary Jane Watson']],
  ['tt0848228', 'The Avengers', 2012, 143, 'Action,Adventure,Sci-Fi', 'United States', 'PG-13', 1519000000, 8.0, 91, 69,
    'A spy agency assembles a group of barely compatible heroes when a stolen artefact opens a portal over Manhattan.',
    'Joss Whedon', ['Robert Downey Jr.:Tony Stark', 'Chris Evans:Steve Rogers', 'Scarlett Johansson:Natasha Romanoff', 'Mark Ruffalo:Bruce Banner']],
  ['tt4154756', 'Avengers: Infinity War', 2018, 149, 'Action,Adventure,Sci-Fi', 'United States', 'PG-13', 2048000000, 8.4, 85, 68,
    'A collector of infinity stones works methodically through the galaxy while every hero alive tries to stop him.',
    'Anthony Russo', ['Robert Downey Jr.:Tony Stark', 'Chris Hemsworth:Thor', 'Josh Brolin:Thanos', 'Scarlett Johansson:Natasha Romanoff']],
  ['tt4154796', 'Avengers: Endgame', 2019, 181, 'Action,Adventure,Drama', 'United States', 'PG-13', 2799000000, 8.4, 94, 78,
    'The survivors of the snap spend five years grieving before a way back presents itself.',
    'Anthony Russo', ['Robert Downey Jr.:Tony Stark', 'Chris Evans:Steve Rogers', 'Mark Ruffalo:Bruce Banner', 'Josh Brolin:Thanos']],
  ['tt2015381', 'Guardians of the Galaxy', 2014, 121, 'Action,Adventure,Comedy', 'United States', 'PG-13', 773000000, 8.0, 92, 76,
    'A thief, an assassin, a literal-minded warrior, a raccoon and a tree are jailed together and decide to save a planet.',
    'James Gunn', ['Chris Pratt:Peter Quill', 'Zoe Saldana:Gamora', 'Dave Bautista:Drax', 'Bradley Cooper:Rocket']],
  ['tt7286456', 'Joker', 2019, 122, 'Crime,Drama,Thriller', 'United States', 'R', 1074000000, 8.3, 68, 59,
    'A failing clown-for-hire in a city that has stopped paying attention finds that violence gets him noticed.',
    'Todd Phillips', ['Joaquin Phoenix:Arthur Fleck', 'Robert De Niro:Murray Franklin', 'Zazie Beetz:Sophie Dumond']],
  ['tt0947798', 'Black Swan', 2010, 108, 'Drama,Thriller', 'United States', 'R', 329000000, 8.0, 85, 79,
    'A ballerina cast in a dual role begins to lose the line between the discipline it demands and her own unravelling.',
    'Darren Aronofsky', ['Natalie Portman:Nina Sayers', 'Mila Kunis:Lily', 'Vincent Cassel:Thomas Leroy', 'Barbara Hershey:Erica']],
  ['tt0180093', 'Requiem for a Dream', 2000, 102, 'Drama', 'United States', 'R', 7400000, 8.3, 78, 71,
    'Four people in Brooklyn chase separate highs through one summer and are taken apart by them by winter.',
    'Darren Aronofsky', ['Ellen Burstyn:Sara Goldfarb', 'Jared Leto:Harry Goldfarb', 'Jennifer Connelly:Marion Silver', 'Marlon Wayans:Tyrone']],
  ['tt1675434', 'The Intouchables', 2011, 112, 'Biography,Comedy,Drama', 'France', 'R', 426000000, 8.5, 76, 57,
    'A quadriplegic aristocrat hires as his carer the one applicant who has no interest in being gentle with him.',
    'Olivier Nakache', ['Francois Cluzet:Philippe', 'Omar Sy:Driss', 'Anne Le Ny:Yvonne']],
  ['tt0119698', 'Princess Mononoke', 1997, 134, 'Animation,Adventure,Fantasy', 'Japan', 'PG-13', 194000000, 8.4, 93, 76,
    'A cursed prince walks into a war between an iron-working town and the gods of the forest it is clearing.',
    'Hayao Miyazaki', ['Yoji Matsuda:Ashitaka', 'Yuriko Ishida:San', 'Yuko Tanaka:Lady Eboshi']],
  ['tt0120586', 'American History X', 1998, 119, 'Drama', 'United States', 'R', 23900000, 8.5, 83, 62,
    'A reformed neo-Nazi comes out of prison to find his younger brother following the path he set.',
    'Tony Kaye', ['Edward Norton:Derek Vinyard', 'Edward Furlong:Danny Vinyard', 'Beverly D’Angelo:Doris Vinyard']],
  ['tt0268978', 'A Beautiful Mind', 2001, 135, 'Biography,Drama', 'United States', 'PG-13', 313000000, 8.2, 74, 72,
    'A mathematician’s breakthrough work runs alongside a delusion he cannot tell apart from his own reasoning.',
    'Ron Howard', ['Russell Crowe:John Nash', 'Jennifer Connelly:Alicia Nash', 'Ed Harris:Parcher', 'Paul Bettany:Charles']],
  ['tt0119217', 'Good Will Hunting', 1997, 126, 'Drama,Romance', 'United States', 'R', 225900000, 8.3, 97, 71,
    'A janitor at MIT solves proofs on a corridor blackboard and is pushed into therapy instead of prison.',
    'Gus Van Sant', ['Matt Damon:Will Hunting', 'Robin Williams:Sean Maguire', 'Ben Affleck:Chuckie Sullivan', 'Minnie Driver:Skylar']],
  ['tt0120689', 'The Green Mile', 1999, 189, 'Crime,Drama,Fantasy', 'United States', 'R', 286800000, 8.6, 78, 61,
    'Guards on a Depression-era death row take charge of a giant of a man convicted of a crime he could not have committed.',
    'Frank Darabont', ['Tom Hanks:Paul Edgecomb', 'Michael Clarke Duncan:John Coffey', 'David Morse:Brutus Howell', 'Bonnie Hunt:Jan Edgecomb']],
  ['tt0088763', 'Back to the Future', 1985, 116, 'Adventure,Comedy,Sci-Fi', 'United States', 'PG', 388000000, 8.5, 93, 87,
    'A teenager is thrown thirty years into the past and has to get his parents together to exist at all.',
    'Robert Zemeckis', ['Michael J. Fox:Marty McFly', 'Christopher Lloyd:Doc Brown', 'Lea Thompson:Lorraine Baines', 'Crispin Glover:George McFly']],
  ['tt0107290', 'Jurassic Park', 1993, 127, 'Adventure,Sci-Fi,Thriller', 'United States', 'PG-13', 1046000000, 8.2, 91, 68,
    'A preview weekend at a park of cloned dinosaurs goes wrong the moment the fences lose power.',
    'Steven Spielberg', ['Sam Neill:Dr. Alan Grant', 'Laura Dern:Dr. Ellie Sattler', 'Jeff Goldblum:Dr. Ian Malcolm', 'Richard Attenborough:John Hammond']],
  ['tt0119654', 'Men in Black', 1997, 98, 'Action,Adventure,Comedy', 'United States', 'PG-13', 589000000, 7.3, 92, 71,
    'A New York cop is recruited into an agency that polices the aliens already living in the city.',
    'Barry Sonnenfeld', ['Tommy Lee Jones:Agent K', 'Will Smith:Agent J', 'Linda Fiorentino:Laurel Weaver', 'Vincent D’Onofrio:Edgar']],
  ['tt0116282', 'Fargo', 1996, 98, 'Crime,Drama,Thriller', 'United States', 'R', 60600000, 8.1, 94, 86,
    'A car salesman hires two men to kidnap his own wife, and a pregnant police chief follows the bodies back to him.',
    'Joel Coen', ['Frances McDormand:Marge Gunderson', 'William H. Macy:Jerry Lundegaard', 'Steve Buscemi:Carl Showalter', 'Peter Stormare:Gaear Grimsrud']],
  ['tt0118715', 'The Big Lebowski', 1998, 117, 'Comedy,Crime', 'United States', 'R', 46700000, 8.1, 83, 71,
    'A slacker mistaken for a millionaire of the same name wants nothing more than his rug replaced.',
    'Joel Coen', ['Jeff Bridges:The Dude', 'John Goodman:Walter Sobchak', 'Julianne Moore:Maude Lebowski', 'Steve Buscemi:Donny']],
  ['tt0477348', 'No Country for Old Men', 2007, 122, 'Crime,Drama,Thriller', 'United States', 'R', 171600000, 8.2, 93, 92,
    'A welder takes a case of drug money from a desert crime scene and is followed by a killer with his own rules.',
    'Joel Coen', ['Tommy Lee Jones:Ed Tom Bell', 'Javier Bardem:Anton Chigurh', 'Josh Brolin:Llewelyn Moss', 'Kelly Macdonald:Carla Jean Moss']],
  ['tt1392214', 'Prisoners', 2013, 153, 'Crime,Drama,Mystery', 'United States', 'R', 122100000, 8.1, 81, 70,
    'When two girls disappear, one father takes the investigation into his own hands while a detective works the case properly.',
    'Denis Villeneuve', ['Hugh Jackman:Keller Dover', 'Jake Gyllenhaal:Detective Loki', 'Viola Davis:Nancy Birch', 'Paul Dano:Alex Jones']],
  ['tt2543164', 'Arrival', 2016, 116, 'Drama,Mystery,Sci-Fi', 'United States', 'PG-13', 203400000, 7.9, 94, 81,
    'A linguist is brought in to work out what twelve arriving craft want before the nations below stop cooperating.',
    'Denis Villeneuve', ['Amy Adams:Louise Banks', 'Jeremy Renner:Ian Donnelly', 'Forest Whitaker:Colonel Weber']],
  ['tt1856101', 'Blade Runner 2049', 2017, 164, 'Action,Drama,Mystery', 'United States', 'R', 267700000, 8.0, 88, 81,
    'A replicant blade runner uncovers a buried record that could undo the order between his kind and their makers.',
    'Denis Villeneuve', ['Ryan Gosling:K', 'Harrison Ford:Rick Deckard', 'Ana de Armas:Joi', 'Sylvia Hoeks:Luv']],
  ['tt1160419', 'Dune', 2021, 155, 'Action,Adventure,Drama', 'United States', 'PG-13', 402000000, 8.0, 83, 74,
    'A ducal heir arrives on a desert world his family has been given to govern, and which was never going to let them.',
    'Denis Villeneuve', ['Timothee Chalamet:Paul Atreides', 'Rebecca Ferguson:Lady Jessica', 'Oscar Isaac:Duke Leto', 'Zendaya:Chani']],
  ['tt0169858', 'Ocean’s Eleven', 2001, 116, 'Crime,Thriller', 'United States', 'PG-13', 450700000, 7.7, 82, 74,
    'A thief out on parole assembles ten specialists to empty three Las Vegas vaults on one night.',
    'Steven Soderbergh', ['George Clooney:Danny Ocean', 'Brad Pitt:Rusty Ryan', 'Matt Damon:Linus Caldwell', 'Julia Roberts:Tess Ocean']],
  ['tt0212720', 'A.I. Artificial Intelligence', 2001, 146, 'Drama,Sci-Fi', 'United States', 'PG-13', 235900000, 7.2, 75, 65,
    'A robot child built to love is abandoned in the woods and spends centuries trying to become real enough to be kept.',
    'Steven Spielberg', ['Haley Joel Osment:David', 'Jude Law:Gigolo Joe', 'Frances O’Connor:Monica Swinton']],
  ['tt0167404', 'The Sixth Sense', 1999, 107, 'Drama,Mystery,Thriller', 'United States', 'PG-13', 672800000, 8.2, 86, 64,
    'A child psychologist takes on a boy who says he sees the dead, and does not question why the boy trusts him.',
    'M. Night Shyamalan', ['Bruce Willis:Malcolm Crowe', 'Haley Joel Osment:Cole Sear', 'Toni Collette:Lynn Sear']],
  ['tt0112573', 'Braveheart', 1995, 178, 'Biography,Drama,History', 'United States', 'R', 213200000, 8.3, 76, 68,
    'A Scottish commoner raises a rebellion against English rule after soldiers kill his wife.',
    'Mel Gibson', ['Mel Gibson:William Wallace', 'Sophie Marceau:Princess Isabelle', 'Patrick McGoohan:Longshanks']],
  ['tt0246578', 'Donnie Darko', 2001, 113, 'Drama,Mystery,Sci-Fi', 'United States', 'R', 7500000, 8.0, 87, 71,
    'A sleepwalking teenager is warned by a figure in a rabbit suit that the world ends in twenty-eight days.',
    'Richard Kelly', ['Jake Gyllenhaal:Donnie Darko', 'Jena Malone:Gretchen Ross', 'Mary McDonnell:Rose Darko', 'Patrick Swayze:Jim Cunningham']],
  ['tt0289879', 'Primer', 2004, 77, 'Drama,Sci-Fi,Thriller', 'United States', 'PG-13', 841926, 6.8, 72, 68,
    'Two engineers building something else in a garage accidentally make a box that moves them backwards through the day.',
    'Shane Carruth', ['Shane Carruth:Aaron', 'David Sullivan:Abe', 'Casey Gooden:Robert']],
  ['tt3170832', 'Room', 2015, 118, 'Drama,Thriller', 'Ireland', 'R', 36300000, 8.1, 93, 86,
    'A woman held captive for seven years plans an escape for the five-year-old who has never seen outside.',
    'Lenny Abrahamson', ['Brie Larson:Ma', 'Jacob Tremblay:Jack', 'Joan Allen:Nancy', 'William H. Macy:Robert']],
  ['tt1798709', 'Her', 2013, 126, 'Drama,Romance,Sci-Fi', 'United States', 'R', 48300000, 8.0, 95, 91,
    'A lonely letter writer in near-future Los Angeles falls in love with the operating system he installs.',
    'Spike Jonze', ['Joaquin Phoenix:Theodore', 'Scarlett Johansson:Samantha', 'Amy Adams:Amy', 'Rooney Mara:Catherine']],
  ['tt0910936', 'Pineapple Express', 2008, 111, 'Action,Comedy,Crime', 'United States', 'R', 101600000, 6.9, 68, 64,
    'A process server and his dealer go on the run after witnessing a murder tied to a rare strain only they smoke.',
    'David Gordon Green', ['Seth Rogen:Dale Denton', 'James Franco:Saul Silver', 'Danny McBride:Red']],
  ['tt0378194', 'Kill Bill: Vol. 2', 2004, 137, 'Action,Crime,Thriller', 'United States', 'R', 152200000, 8.0, 84, 83,
    'The Bride works through the last names on her list and finds out what was taken from her.',
    'Quentin Tarantino', ['Uma Thurman:The Bride', 'David Carradine:Bill', 'Daryl Hannah:Elle Driver', 'Michael Madsen:Budd']],
  ['tt0266697', 'Kill Bill: Vol. 1', 2003, 111, 'Action,Crime,Thriller', 'United States', 'R', 180900000, 8.2, 85, 69,
    'A former assassin wakes from a four-year coma and starts crossing names off a list.',
    'Quentin Tarantino', ['Uma Thurman:The Bride', 'Lucy Liu:O-Ren Ishii', 'Vivica A. Fox:Vernita Green', 'Sonny Chiba:Hattori Hanzo']],
  ['tt0105236', 'Reservoir Dogs', 1992, 99, 'Crime,Drama,Thriller', 'United States', 'R', 2900000, 8.3, 90, 81,
    'Six strangers given colour names regroup in a warehouse after a diamond heist that was clearly set up.',
    'Quentin Tarantino', ['Harvey Keitel:Mr. White', 'Tim Roth:Mr. Orange', 'Michael Madsen:Mr. Blonde', 'Steve Buscemi:Mr. Pink']],
  ['tt0119488', 'L.A. Confidential', 1997, 138, 'Crime,Drama,Mystery', 'United States', 'R', 126200000, 8.2, 99, 91,
    'Three Los Angeles officers with nothing in common work the same 1950s diner shooting from three directions.',
    'Curtis Hanson', ['Guy Pearce:Ed Exley', 'Russell Crowe:Bud White', 'Kevin Spacey:Jack Vincennes', 'Kim Basinger:Lynn Bracken']],
  ['tt0264464', 'Catch Me If You Can', 2002, 141, 'Biography,Crime,Drama', 'United States', 'PG-13', 352100000, 8.1, 96, 75,
    'A teenage forger passes as a pilot, a doctor and a lawyer while the FBI agent chasing him becomes the closest thing he has to family.',
    'Steven Spielberg', ['Leonardo DiCaprio:Frank Abagnale Jr.', 'Tom Hanks:Carl Hanratty', 'Christopher Walken:Frank Abagnale Sr.']],
  ['tt0257044', 'The Bourne Identity', 2002, 119, 'Action,Mystery,Thriller', 'United States', 'PG-13', 214000000, 7.9, 84, 68,
    'A man pulled from the Mediterranean with no memory finds he is very good at things he cannot account for.',
    'Doug Liman', ['Matt Damon:Jason Bourne', 'Franka Potente:Marie', 'Chris Cooper:Conklin', 'Clive Owen:The Professor']],
  ['tt1631867', 'Edge of Tomorrow', 2014, 113, 'Action,Adventure,Sci-Fi', 'United States', 'PG-13', 370500000, 7.9, 91, 71,
    'A public relations officer dropped into an unwinnable invasion restarts the same day every time he dies.',
    'Doug Liman', ['Tom Cruise:Cage', 'Emily Blunt:Rita Vrataski', 'Bill Paxton:Master Sergeant Farell']],
  ['tt0325980', 'Pirates of the Caribbean: The Curse of the Black Pearl', 2003, 143, 'Action,Adventure,Fantasy', 'United States', 'PG-13', 654300000, 8.1, 79, 63,
    'A blacksmith joins a deposed pirate captain to rescue a governor’s daughter from a crew that cannot die.',
    'Gore Verbinski', ['Johnny Depp:Jack Sparrow', 'Orlando Bloom:Will Turner', 'Keira Knightley:Elizabeth Swann', 'Geoffrey Rush:Barbossa']],
  ['tt0758758', 'Into the Wild', 2007, 148, 'Adventure,Biography,Drama', 'United States', 'R', 56300000, 8.1, 83, 73,
    'A graduate gives away his savings and walks north, keeping a journal until Alaska stops being survivable.',
    'Sean Penn', ['Emile Hirsch:Christopher McCandless', 'Hal Holbrook:Ron Franz', 'Catherine Keener:Jan Burres']],
  ['tt0790636', 'Dallas Buyers Club', 2013, 117, 'Biography,Drama', 'United States', 'R', 55200000, 7.9, 92, 84,
    'A Texas electrician given thirty days to live starts importing unapproved drugs for himself and then for everyone.',
    'Jean-Marc Vallee', ['Matthew McConaughey:Ron Woodroof', 'Jared Leto:Rayon', 'Jennifer Garner:Dr. Eve Saks']],
  ['tt2024544', '12 Years a Slave', 2013, 134, 'Biography,Drama,History', 'United States', 'R', 187700000, 8.1, 95, 96,
    'A free Black musician in New York is drugged, sold south, and spends twelve years trying to get word home.',
    'Steve McQueen', ['Chiwetel Ejiofor:Solomon Northup', 'Michael Fassbender:Edwin Epps', 'Lupita Nyong’o:Patsey', 'Benedict Cumberbatch:Ford']],
  ['tt5052448', 'Get Out', 2017, 104, 'Horror,Mystery,Thriller', 'United States', 'R', 255400000, 7.7, 98, 85,
    'A photographer meets his white girlfriend’s family for the first time and finds the weekend is not about him at all.',
    'Jordan Peele', ['Daniel Kaluuya:Chris Washington', 'Allison Williams:Rose Armitage', 'Bradley Whitford:Dean Armitage', 'Catherine Keener:Missy Armitage']],
];

const PEOPLE_BIRTH = {
  'Tim Robbins': 1958, 'Morgan Freeman': 1937, 'Bob Gunton': 1945, 'William Sadler': 1950,
  'John Travolta': 1954, 'Samuel L. Jackson': 1948, 'Uma Thurman': 1970, 'Bruce Willis': 1955,
  'Liam Neeson': 1952, 'Ben Kingsley': 1943, 'Ralph Fiennes': 1962, 'Tom Hanks': 1956,
  'Robin Wright': 1966, 'Gary Sinise': 1955, 'Sally Field': 1946, 'Jodie Foster': 1962,
  'Anthony Hopkins': 1937, 'Scott Glenn': 1941, 'Brad Pitt': 1963, 'Gwyneth Paltrow': 1972,
  'Kevin Spacey': 1959, 'Edward Norton': 1969, 'Helena Bonham Carter': 1966, 'Keanu Reeves': 1964,
  'Laurence Fishburne': 1961, 'Carrie-Anne Moss': 1967, 'Hugo Weaving': 1960, 'Tom Sizemore': 1961,
  'Matt Damon': 1970, 'Elijah Wood': 1981, 'Ian McKellen': 1939, 'Viggo Mortensen': 1958,
  'Sean Astin': 1971, 'Andy Serkis': 1964, 'Christian Bale': 1974, 'Heath Ledger': 1979,
  'Aaron Eckhart': 1968, 'Gary Oldman': 1958, 'Michael Caine': 1933, 'Cillian Murphy': 1976,
  'Leonardo DiCaprio': 1974, 'Joseph Gordon-Levitt': 1981, 'Elliot Page': 1987, 'Tom Hardy': 1977,
  'Matthew McConaughey': 1969, 'Anne Hathaway': 1982, 'Jessica Chastain': 1977, 'Guy Pearce': 1967,
  'Joe Pantoliano': 1951, 'Hugh Jackman': 1968, 'Scarlett Johansson': 1984, 'Russell Crowe': 1964,
  'Joaquin Phoenix': 1974, 'Connie Nielsen': 1965, 'Jim Carrey': 1962, 'Kate Winslet': 1975,
  'Kirsten Dunst': 1982, 'Mark Ruffalo': 1967, 'Jack Nicholson': 1937, 'Mark Wahlberg': 1971,
  'Jonah Hill': 1983, 'Margot Robbie': 1990, 'Christoph Waltz': 1956, 'Diane Kruger': 1976,
  'Jamie Foxx': 1967, 'Miles Teller': 1987, 'J.K. Simmons': 1955, 'Ryan Gosling': 1980,
  'Emma Stone': 1988, 'Charlize Theron': 1975, 'Nicholas Hoult': 1989, 'Ben Affleck': 1972,
  'Rosamund Pike': 1979, 'Gabriel Byrne': 1950, 'Benicio del Toro': 1967, 'Annette Bening': 1958,
  'Adrien Brody': 1973, 'John Goodman': 1952, 'Billy Crystal': 1948, 'Steve Buscemi': 1957,
  'Albert Brooks': 1947, 'Ellen DeGeneres': 1958, 'Willem Dafoe': 1955, 'Sigourney Weaver': 1949,
  'Amy Poehler': 1971, 'Bill Hader': 1978, 'Holly Hunter': 1958, 'Patton Oswalt': 1969,
  'Gerard Butler': 1969, 'Gael Garcia Bernal': 1978, 'Tony Revolori': 1996, 'Saoirse Ronan': 1994,
  'Gene Hackman': 1930, 'Anjelica Huston': 1951, 'Ben Stiller': 1965, 'Tobey Maguire': 1975,
  'Alfred Molina': 1953, 'James Franco': 1978, 'Robert Downey Jr.': 1965, 'Chris Evans': 1981,
  'Chris Hemsworth': 1983, 'Josh Brolin': 1968, 'Chris Pratt': 1979, 'Zoe Saldana': 1978,
  'Bradley Cooper': 1975, 'Robert De Niro': 1943, 'Natalie Portman': 1981, 'Mila Kunis': 1983,
  'Vincent Cassel': 1966, 'Ellen Burstyn': 1932, 'Jared Leto': 1971, 'Jennifer Connelly': 1970,
  'Omar Sy': 1978, 'Edward Furlong': 1977, 'Ed Harris': 1950, 'Paul Bettany': 1971,
  'Robin Williams': 1951, 'Minnie Driver': 1970, 'Michael Clarke Duncan': 1957,
  'Michael J. Fox': 1961, 'Christopher Lloyd': 1938, 'Sam Neill': 1947, 'Laura Dern': 1967,
  'Jeff Goldblum': 1952, 'Richard Attenborough': 1923, 'Tommy Lee Jones': 1946, 'Will Smith': 1968,
  'Frances McDormand': 1957, 'William H. Macy': 1950, 'Jeff Bridges': 1949, 'Julianne Moore': 1960,
  'Javier Bardem': 1969, 'Jake Gyllenhaal': 1980, 'Viola Davis': 1965, 'Paul Dano': 1984,
  'Amy Adams': 1974, 'Jeremy Renner': 1971, 'Forest Whitaker': 1961, 'Harrison Ford': 1942,
  'Ana de Armas': 1988, 'Timothee Chalamet': 1995, 'Rebecca Ferguson': 1983, 'Oscar Isaac': 1979,
  'Zendaya': 1996, 'George Clooney': 1961, 'Julia Roberts': 1967, 'Haley Joel Osment': 1988,
  'Jude Law': 1972, 'Toni Collette': 1972, 'Mel Gibson': 1956, 'Jena Malone': 1984,
  'Brie Larson': 1989, 'Jacob Tremblay': 2006, 'Joan Allen': 1956, 'Seth Rogen': 1982,
  'Lucy Liu': 1968, 'Harvey Keitel': 1939, 'Tim Roth': 1961, 'Michael Madsen': 1957,
  'Kim Basinger': 1953, 'Christopher Walken': 1943, 'Franka Potente': 1974, 'Tom Cruise': 1962,
  'Emily Blunt': 1983, 'Johnny Depp': 1963, 'Orlando Bloom': 1977, 'Keira Knightley': 1985,
  'Geoffrey Rush': 1951, 'Emile Hirsch': 1985, 'Chiwetel Ejiofor': 1977, 'Michael Fassbender': 1977,
  'Benedict Cumberbatch': 1976, 'Daniel Kaluuya': 1989, 'Catherine Keener': 1959,
  'Christopher Nolan': 1970, 'Quentin Tarantino': 1963, 'Steven Spielberg': 1946,
  'Martin Scorsese': 1942, 'David Fincher': 1962, 'Peter Jackson': 1961, 'Ridley Scott': 1937,
  'Hayao Miyazaki': 1941, 'Wes Anderson': 1969, 'Denis Villeneuve': 1967, 'Damien Chazelle': 1985,
  'Bong Joon Ho': 1969, 'Joel Coen': 1954, 'Darren Aronofsky': 1969, 'Sam Raimi': 1959,
  'Frank Darabont': 1959, 'Robert Zemeckis': 1951, 'Pete Docter': 1968, 'Brad Bird': 1957,
  'Andrew Stanton': 1965, 'Jordan Peele': 1979, 'Steve McQueen': 1969, 'Spike Jonze': 1969,
  'Doug Liman': 1965, 'Alejandro G. Inarritu': 1963, 'George Miller': 1945, 'Todd Phillips': 1970,
};

const PEOPLE_DEATH = {
  'Heath Ledger': 2008, 'Michael Clarke Duncan': 2012, 'Richard Attenborough': 2014,
  'Robin Williams': 2014, 'Gene Hackman': 2025, 'Oliver Reed': 1999, 'Patrick Swayze': 2009,
  'Don Rickles': 2017, 'Ned Beatty': 2021, 'Edward Asner': 2021, 'Bill Paxton': 2017,
  'David Carradine': 2009, 'Peter O’Toole': 2013, 'Sonny Chiba': 2021, 'Hal Holbrook': 2021,
  'Patrick McGoohan': 2009, 'Hugh Keays-Byrne': 2020, 'Tom Sizemore': 2023, 'Ulrich Muhe': 2007,
  'Lee Sun-kyun': 2023, 'Frank Finlay': 2016, 'Hitoshi Takagi': 2004, 'Christopher Plummer': 2021,
  'Sally Field': null,
};

/** Stable synthetic person ids — these are sample data, not real IMDB nconsts. */
const people = new Map();
let personCounter = 0;

function personId(name) {
  if (!people.has(name)) {
    personCounter += 1;
    people.set(name, {
      nconst: `nm${String(9000000 + personCounter)}`,
      primaryName: name,
      birthYear: PEOPLE_BIRTH[name] ?? null,
      deathYear: PEOPLE_DEATH[name] ?? null,
      knownForTitles: [],
    });
  }

  return people.get(name);
}

const movies = [];
const principals = [];
const ratings = [];

for (const film of FILMS) {
  const [tconst, primaryTitle, year, runtimeMinutes, genres, country, rated, boxoffice,
    imdbRating, rottenTomatoesRating, metacriticRating, plot, director, cast] = film;

  movies.push({
    tconst,
    primaryTitle,
    year,
    runtimeMinutes,
    genres,
    country,
    rated,
    boxoffice: boxoffice || null,
    // Rendered client-side from the title; see src/utils/poster.js in the web app.
    poster: null,
    plot,
    imdbRating,
    rottenTomatoesRating,
    metacriticRating,
  });

  ratings.push(
    { tconst, source: 'Internet Movie Database', value: `${imdbRating.toFixed(1)}/10` },
    { tconst, source: 'Rotten Tomatoes', value: `${rottenTomatoesRating}%` },
    { tconst, source: 'Metacritic', value: `${metacriticRating}/100` }
  );

  const dir = personId(director);
  dir.knownForTitles.push(tconst);
  principals.push({ tconst, nconst: dir.nconst, category: 'director', name: director, characters: '' });

  for (const entry of cast) {
    const splitAt = entry.indexOf(':');
    const actorName = entry.slice(0, splitAt);
    const character = entry.slice(splitAt + 1);
    const actor = personId(actorName);
    actor.knownForTitles.push(tconst);
    principals.push({
      tconst,
      nconst: actor.nconst,
      category: 'actor',
      name: actorName,
      characters: JSON.stringify([character]),
    });
  }
}

const names = [...people.values()].map((person) => ({
  nconst: person.nconst,
  primaryName: person.primaryName,
  birthYear: person.birthYear,
  deathYear: person.deathYear,
  knownForTitles: person.knownForTitles.slice(0, 4).join(','),
}));

const outDir = path.join(__dirname, '..', 'data', 'seed');
fs.mkdirSync(outDir, { recursive: true });

const write = (file, rows) => {
  fs.writeFileSync(path.join(outDir, file), `${JSON.stringify(rows, null, 2)}\n`);
  console.log(`${file.padEnd(18)} ${rows.length} rows`);
};

write('basics.json', movies);
write('names.json', names);
write('principals.json', principals);
write('ratings.json', ratings);
